# Generated by Django 3.2.8 on 2021-11-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_like_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_url',
            field=models.CharField(default='https://www.alphr.com/wp-content/uploads/2020/10/twitter.png', max_length=300),
        ),
    ]
